title: Alexander Watson Counselling
description: Thoughtful, person-centred counselling in Greater Manchester and online.
url: https://alexanderwatsoncounselling.co.uk
baseurl: ""
lang: en-GB
timezone: Europe/London

markdown: kramdown
permalink: pretty

exclude:
  - README.md
  - docs
  - Gemfile
  - Gemfile.lock